# Config File Template for Adsorbate Depositor

substrate:
  sites: >
    [
    "1",                           # single site: top
    "2_3",                         # double site: bridge
    "4_5_6",                       # triple site: centroid
    "7_8_9_10"                     # multiple site: centroid
    ]

adsorbate:
  source: "POSCAR"                 # or "DATABASE"
  path: None                       # path to POSCAR file or DATABASE dir
  atom_indexes: None               # required for "POSCAR"-sourced adsorbate generation, adsorbate atom indexes
  reference: None                  # required for "POSCAR"-sourced adsorbate generation, reference point (or "CENTROID")
  pathway_name: "pathway_1"        # required for "DATABASE"-sourced adsorbate generation, pathway name
  rotation: True                   # generate rotated adsorbates

deposit:
  distance: 2.0                    # distance of adsorbate reference point to selected site (in Ã…)
  auto_reposition_along_z: True    # auto adjust z-position
